### ISSUE TITLE
Cannot handle UTF-8 characters

### ISSUE THREAD

**Issue by kseistrup** [hughbarney/atto#3]
I compiled `atto` on a RaspberryPi2 (armv7h) with termcap-1.3.1.

When I entered `Frække frølår` in a buffer, `atto` displayed  `Fr  kke fr  l  r` but the file had the right contents.

Linking with `ncursesw6` instead of `curses` didn't help.

Any suggestions?

**Comment by hughbarney** [comment]
Atto does not currently support UTF8.  Its something I will have to look
into at some point.   I have no plans to work on Atto for a couple of
months as I am quite busy at work now.

**Comment by kseistrup** [comment]
That's fine. Let's leave this issue open as a reminder.

**Comment by hughbarney** [comment]
Pleased to report this is now fixed in Atto 1.12
